module.exports = {
  daemon_mode: true,
  pmx: true,
  pm2_concurrent_actions: 2,
  pm2_log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
  error: true,
  log_type: 'json',
  merge_logs: true,
  autorestart: true,
  max_restarts: 10,
  min_uptime: '10s',
  listen_timeout: 8000,
  kill_timeout: 5000,
  shutdown_with_message: true,
  wait_ready: false,
  max_memory_restart: '1G',
  restart_delay: 4000,
  exp_backoff_restart_delay: 100,
  vizion: false,
  post_update: [],
  force: false,
  automation: true,
  treekill: true,
  instance_var: 'INSTANCE_ID',
  windowsHide: true
};
