[install]
peer = true

[run]
bun = true

[loader]
".flow" = "text"

[define]
"process.env.NODE_ENV" = "\"development\""

# Exclude React Native from backend builds
[backend]
external = ["react-native", "react-native-web", "expo", "expo-*"]
