#!/bin/bash

echo "🔐 Firebase Authentication - Manual Method"
echo ""
echo "Since the OAuth redirect doesn't work in this environment,"
echo "we'll use the CI token method:"
echo ""
echo "1. Open this URL in your browser:"
echo "   https://console.firebase.google.com/"
echo ""
echo "2. Select your project: Kompa2Go"
echo ""
echo "3. Go to Project Settings > Service Accounts"
echo ""
echo "4. Click 'Generate New Private Key'"
echo ""
echo "5. Save the JSON file as 'firebase-service-account.json' in this directory"
echo ""
echo "Then run: chmod +x deploy-with-service-account.sh && ./deploy-with-service-account.sh"
