import React, { createContext, useContext, useState, ReactNode, useMemo, useCallback } from 'react';

type Language = 'es' | 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    // Navigation
    'welcome': 'Bienvenido',
    'search': 'Buscar',
    'services': 'Servicios',
    'profile': 'Perfil',
    'chat': 'Chat',
    'home': 'Inicio',
    'calendar': 'Calendario',
    'analytics': 'Analytics',
    'notifications': 'Notificaciones',
    
    // Common
    'loading': 'Cargando...',
    'error': 'Error',
    'success': 'Éxito',
    'cancel': 'Cancelar',
    'confirm': 'Confirmar',
    'save': 'Guardar',
    'edit': 'Editar',
    'delete': 'Eliminar',
    'back': 'Atrás',
    'next': 'Siguiente',
    'previous': 'Anterior',
    'close': 'Cerrar',
    
    // Auth
    'login': 'Iniciar Sesión',
    'register': 'Registrarse',
    'logout': 'Cerrar Sesión',
    'email': 'Correo electrónico',
    'password': 'Contraseña',
    'name': 'Nombre',
    'phone': 'Teléfono',
    'location': 'Ubicación',
    
    // Kompa2Go specific
    'slogan': 'Tu servicio, a un toque',
    'find_book_enjoy': 'Busca, reserva, disfruta. Así de fácil.',
    'share_location': 'Compartir ubicación',
    'ask_kompi': 'Pregunta a Kompi',
    'featured_providers': 'Proveedores Destacados',
    'service_categories': 'Categorías de Servicios',
    'my_wallet': 'Mi Billetera',
    'okoins': 'OKoins',
    'booking_passes': 'Pases de Reserva',
    'loyalty_points': 'Puntos de lealtad',
    'available_balance': 'Saldo disponible',
    'available_passes': 'Pases disponibles',
    'buy_pass': 'Comprar Pase',
    'upcoming_appointments': 'Próximas Citas',
    'no_appointments': 'No tienes citas programadas',
    'popular_services': 'Servicios Populares',
    'manage_business': 'Gestiona tu negocio',
    'appointments_today': 'Citas Hoy',
    'rating': 'Calificación',
    'view_calendar': 'Ver Calendario',
    'collaborators': 'Colaboradores',
    'admin_panel': 'Panel de Administración',
    'system_overview': 'Resumen del sistema',
    'users': 'Usuarios',
    'providers': 'Proveedores',
    'bookings_today': 'Reservas Hoy',
    'revenue': 'Ingresos',
    'quick_actions': 'Acciones Rápidas',
    'manage_users': 'Gestionar Usuarios',
    'approve_providers': 'Aprobar Proveedores',
    'view_transactions': 'Ver Transacciones',
    'test_users': 'Pruebas de Usuario',
    'switch_to_client_provider': 'Cambiar a Cliente/Proveedor',
    'switch_role': 'Cambiar Rol',
    'select_role': 'Seleccionar Rol',
    'client_mikompa': 'Mi-Kompa (Cliente)',
    'provider_2kompa': '2-Kompa (Proveedor)',
    'enter_credentials': 'Ingresa las credenciales',
    'switching': 'Cambiando...',
    'change_role': 'Cambiar Rol',
    'language': 'Idioma',
    'spanish': 'Español',
    'english': 'Inglés',
    'portuguese': 'Portugués',
    
    // Home screen
    'hello': '¡Hola',
    'what_service_today': '¿Qué servicio necesitas hoy?',
    'wallet_balance': 'Saldo disponible',
    'buy_pass_price': 'Comprar Pase (₡500)',
    'search_services': 'Buscar Servicios',
    'switch_to_test_user': 'Cambiar a Usuario de Prueba',
    'enter_test_credentials': 'Ingresa las credenciales del usuario de prueba:',
    
    // Search screen
    'search_services_title': 'Buscar Servicios',
    'what_service_need': '¿Qué servicio necesitas?',
    'categories': 'Categorías',
    'providers_count': 'proveedores',
    'ask_kompi_what_need': 'Pregunta a Kompi qué necesitas',
    
    // Profile screen
    'sign_out': 'Cerrar Sesión',
    'sign_out_confirm': '¿Estás seguro que deseas cerrar sesión?',
    'edit_profile': 'Editar Perfil',
    'update_personal_info': 'Actualiza tu información personal',
    'manage_credits_payments': 'Gestiona tus créditos y pagos',
    'history': 'Historial',
    'view_previous_bookings': 'Ver tus reservas anteriores',
    'configuration': 'Configuración',
    'app_preferences': 'Preferencias de la aplicación',
    'my_calendar': 'Mi Calendario',
    'manage_availability': 'Gestiona tu disponibilidad',
    'manage_team': 'Administra tu equipo',
    'manage_platform': 'Administrar la plataforma',
    'user': 'Usuario',
    'administrator': 'Administrador',
    'client': 'Cliente',
    'provider': 'Proveedor',
    'available_credits': 'Créditos disponibles',
    'add_credits': 'Agregar Créditos',
    'statistics': 'Estadísticas',
    'income': 'Ingresos',
    
    // Calendar screen
    'month': 'Mes',
    'day': 'Día',
    'back_to_month': 'Volver al Mes',
    'day_agenda': 'Agenda del Día',
    'available': 'Disponible',
    'add_manual_appointment': 'Agregar Cita Manual',
    'block_time': 'Bloquear Tiempo',
    'function_providers_only': 'Esta función es solo para proveedores',
    'client_required': 'Cliente *',
    'service_required': 'Servicio *',
    'time_required': 'Hora *',
    'collaborator_optional': 'Colaborador',
    'client_name': 'Nombre del cliente',
    'service_type': 'Tipo de servicio',
    'time_format': 'HH:MM (ej: 14:30)',
    'assign_collaborator': 'Asignar a colaborador (opcional)',
    'full_name_required': 'Nombre Completo *',
    'alias_required': 'Alias *',
    'collaborator_name': 'Nombre del colaborador',
    'short_name': 'Nombre corto o apodo',
    'avatar': 'Avatar',
    'cancel_kompa2go_booking': 'Cancelar Reserva Kompa2Go',
    'cancel_penalty_warning': 'Cancelar esta reserva resultará en una penalización de 4 horas sin aparecer en búsquedas. ¿Continuar?',
    'delete_entry': 'Eliminar',
    'delete_entry_confirm': '¿Estás seguro de que quieres eliminar esta entrada?',
    'appointment_added': 'Cita agregada correctamente',
    'collaborator_added': 'Colaborador agregado correctamente',
    'complete_required_fields': 'Por favor completa todos los campos obligatorios',
    'complete_name_alias': 'Por favor completa el nombre y alias',
    'appointments_for': 'Citas para',
    'date_required': 'Fecha *',
    'is_today': 'Es hoy',
    'select_date': 'Seleccionar fecha',
    'select_time': 'Seleccionar hora',
    'no_collaborator': 'Sin colaborador',
    'assigned_to': 'Asignado a',
    'scheduling_conflict': 'Conflicto de horario',
    'conflict_error_message': 'Conflicto de horario. Este horario ya está ocupado por otra cita o está bloqueado. Por favor elige un horario diferente o modifica el bloqueo en tu calendario principal.',
    'ok': 'OK',
    'error_adding_appointment': 'Error al agregar la cita',
    
    // Provider Dashboard
    'programs': 'Programas',
    'sakura_contigo': 'Sakura Contigo',
    'kompa2door': 'Kompa2Door',
    'kraffles': 'Kraffles',
    'program_locked': 'Programa bloqueado',
    'unlock_requirements': 'Requisitos para desbloquear',
    'achievements_required': 'Logros requeridos',
    'cost': 'Costo',
    'collaborators_management': 'Gestión de Colaboradores',
    'edit_collaborator': 'Editar Colaborador',
    'block_collaborator': 'Bloquear Colaborador',
    'delete_collaborator': 'Eliminar Colaborador',
    'create_credentials': 'Crear Credenciales',
    'username': 'Usuario',
    'assign_services': 'Asignar Servicios',
    'historical': 'Historial',
    'completed_services': 'Servicios Completados',
    'complaint_filed': 'Queja presentada',
    'complaint_details': 'Detalles de la queja',
    'anonymous_complaint': 'Queja anónima',
    'improvement_plan': 'Plan de mejora',
    'configurations': 'Configuraciones',
    'service_management': 'Gestión de Servicios',
    'add_service': 'Agregar Servicio',
    'modify_service_restriction': 'Solo puedes modificar servicios después de 3 meses de actividad',
    'profile_management': 'Gestión de Perfil',
    'business_name': 'Nombre del Negocio',
    'work_gallery': 'Galería de Trabajos',
    'brand_logo': 'Logo de Marca',
    'promotions': 'Promociones',
    'promotions_locked': 'Promociones bloqueadas hasta desbloquear logros',
    'rating_summary': 'Resumen de Calificaciones',
    'total_rated_services': 'Total de servicios calificados',
    'rating_tips': 'Consejos para mantener alta calificación',
    'services_analytics': 'Análisis de Servicios',
    'most_popular_services': 'Servicios más populares',
    'revenue_breakdown': 'Desglose de Ingresos',
    'filter_by_day': 'Filtrar por día',
    'filter_by_week': 'Filtrar por semana',
    'filter_by_month': 'Filtrar por mes',
    'yearly_comparison': 'Comparación anual',
    'revenue_improvement_guide': 'Guía para mejorar ingresos',
    
    // Enhanced Calendar System
    'team_calendar_overview': 'Vista General del Calendario del Equipo',
    'consolidated_view_all_team_events': 'Vista consolidada de todos los eventos del equipo',
    'manual_appointment': 'Cita Manual',
    'blocked_time': 'Tiempo Bloqueado',
    'day_off': 'Día Libre',
    'total_appointments': 'Total de citas',
    'team_consolidated_view': 'Vista consolidada del equipo',
    'unknown_collaborator': 'Colaborador desconocido',
    'unknown': 'Desconocido',
    'add_collaborator': 'Agregar Colaborador',
  },
  en: {
    // Navigation
    'welcome': 'Welcome',
    'search': 'Search',
    'services': 'Services',
    'profile': 'Profile',
    'chat': 'Chat',
    'home': 'Home',
    'calendar': 'Calendar',
    'analytics': 'Analytics',
    'notifications': 'Notifications',
    
    // Common
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'close': 'Close',
    
    // Auth
    'login': 'Login',
    'register': 'Register',
    'logout': 'Logout',
    'email': 'Email',
    'password': 'Password',
    'name': 'Name',
    'phone': 'Phone',
    'location': 'Location',
    
    // Kompa2Go specific
    'slogan': 'Your service, one touch away',
    'find_book_enjoy': 'Find, book, enjoy. It\'s that easy.',
    'share_location': 'Share location',
    'ask_kompi': 'Ask Kompi',
    'featured_providers': 'Featured Providers',
    'service_categories': 'Service Categories',
    'my_wallet': 'My Wallet',
    'okoins': 'OKoins',
    'booking_passes': 'Booking Passes',
    'loyalty_points': 'Loyalty points',
    'available_balance': 'Available balance',
    'available_passes': 'Available passes',
    'buy_pass': 'Buy Pass',
    'upcoming_appointments': 'Upcoming Appointments',
    'no_appointments': 'No scheduled appointments',
    'popular_services': 'Popular Services',
    'manage_business': 'Manage your business',
    'appointments_today': 'Appointments Today',
    'rating': 'Rating',
    'view_calendar': 'View Calendar',
    'collaborators': 'Collaborators',
    'admin_panel': 'Admin Panel',
    'system_overview': 'System overview',
    'users': 'Users',
    'providers': 'Providers',
    'bookings_today': 'Bookings Today',
    'revenue': 'Revenue',
    'quick_actions': 'Quick Actions',
    'manage_users': 'Manage Users',
    'approve_providers': 'Approve Providers',
    'view_transactions': 'View Transactions',
    'test_users': 'Test Users',
    'switch_to_client_provider': 'Switch to Client/Provider',
    'switch_role': 'Switch Role',
    'select_role': 'Select Role',
    'client_mikompa': 'Mi-Kompa (Client)',
    'provider_2kompa': '2-Kompa (Provider)',
    'enter_credentials': 'Enter credentials',
    'switching': 'Switching...',
    'change_role': 'Change Role',
    'language': 'Language',
    'spanish': 'Spanish',
    'english': 'English',
    'portuguese': 'Portuguese',
    
    // Home screen
    'hello': 'Hello',
    'what_service_today': 'What service do you need today?',
    'wallet_balance': 'Available balance',
    'buy_pass_price': 'Buy Pass (₡500)',
    'search_services': 'Search Services',
    'switch_to_test_user': 'Switch to Test User',
    'enter_test_credentials': 'Enter test user credentials:',
    
    // Search screen
    'search_services_title': 'Search Services',
    'what_service_need': 'What service do you need?',
    'categories': 'Categories',
    'providers_count': 'providers',
    'ask_kompi_what_need': 'Ask Kompi what you need',
    
    // Profile screen
    'sign_out': 'Sign Out',
    'sign_out_confirm': 'Are you sure you want to sign out?',
    'edit_profile': 'Edit Profile',
    'update_personal_info': 'Update your personal information',
    'manage_credits_payments': 'Manage your credits and payments',
    'history': 'History',
    'view_previous_bookings': 'View your previous bookings',
    'configuration': 'Configuration',
    'app_preferences': 'App preferences',
    'my_calendar': 'My Calendar',
    'manage_availability': 'Manage your availability',
    'manage_team': 'Manage your team',
    'manage_platform': 'Manage the platform',
    'user': 'User',
    'administrator': 'Administrator',
    'client': 'Client',
    'provider': 'Provider',
    'available_credits': 'Available credits',
    'add_credits': 'Add Credits',
    'statistics': 'Statistics',
    'income': 'Income',
    
    // Calendar screen
    'month': 'Month',
    'day': 'Day',
    'back_to_month': 'Back to Month',
    'day_agenda': 'Day Agenda',
    'available': 'Available',
    'add_manual_appointment': 'Add Manual Appointment',
    'block_time': 'Block Time',
    'function_providers_only': 'This function is for providers only',
    'client_required': 'Client *',
    'service_required': 'Service *',
    'time_required': 'Time *',
    'collaborator_optional': 'Collaborator',
    'client_name': 'Client name',
    'service_type': 'Service type',
    'time_format': 'HH:MM (e.g: 14:30)',
    'assign_collaborator': 'Assign to collaborator (optional)',
    'full_name_required': 'Full Name *',
    'alias_required': 'Alias *',
    'collaborator_name': 'Collaborator name',
    'short_name': 'Short name or nickname',
    'avatar': 'Avatar',
    'cancel_kompa2go_booking': 'Cancel Kompa2Go Booking',
    'cancel_penalty_warning': 'Canceling this booking will result in a 4-hour penalty without appearing in searches. Continue?',
    'delete_entry': 'Delete',
    'delete_entry_confirm': 'Are you sure you want to delete this entry?',
    'appointment_added': 'Appointment added successfully',
    'collaborator_added': 'Collaborator added successfully',
    'complete_required_fields': 'Please complete all required fields',
    'complete_name_alias': 'Please complete name and alias',
    'appointments_for': 'Appointments for',
    'date_required': 'Date *',
    'is_today': 'Is today',
    'select_date': 'Select date',
    'select_time': 'Select time',
    'no_collaborator': 'No collaborator',
    'assigned_to': 'Assigned to',
    'scheduling_conflict': 'Scheduling conflict',
    'conflict_error_message': 'Scheduling conflict. This time slot is already blocked or has an existing appointment. Please choose a different time or modify the block in your main calendar.',
    'ok': 'OK',
    'error_adding_appointment': 'Error adding appointment',
    
    // Provider Dashboard
    'programs': 'Programs',
    'sakura_contigo': 'Sakura Contigo',
    'kompa2door': 'Kompa2Door',
    'kraffles': 'Kraffles',
    'program_locked': 'Program locked',
    'unlock_requirements': 'Unlock requirements',
    'achievements_required': 'Achievements required',
    'cost': 'Cost',
    'collaborators_management': 'Collaborators Management',
    'edit_collaborator': 'Edit Collaborator',
    'block_collaborator': 'Block Collaborator',
    'delete_collaborator': 'Delete Collaborator',
    'create_credentials': 'Create Credentials',
    'username': 'Username',
    'assign_services': 'Assign Services',
    'historical': 'History',
    'completed_services': 'Completed Services',
    'complaint_filed': 'Complaint filed',
    'complaint_details': 'Complaint details',
    'anonymous_complaint': 'Anonymous complaint',
    'improvement_plan': 'Improvement plan',
    'configurations': 'Settings',
    'service_management': 'Service Management',
    'add_service': 'Add Service',
    'modify_service_restriction': 'You can only modify services after 3 months of activity',
    'profile_management': 'Profile Management',
    'business_name': 'Business Name',
    'work_gallery': 'Work Gallery',
    'brand_logo': 'Brand Logo',
    'promotions': 'Promotions',
    'promotions_locked': 'Promotions locked until achievements unlocked',
    'rating_summary': 'Rating Summary',
    'total_rated_services': 'Total rated services',
    'rating_tips': 'Tips to maintain high rating',
    'services_analytics': 'Services Analytics',
    'most_popular_services': 'Most popular services',
    'revenue_breakdown': 'Revenue Breakdown',
    'filter_by_day': 'Filter by day',
    'filter_by_week': 'Filter by week',
    'filter_by_month': 'Filter by month',
    'yearly_comparison': 'Yearly comparison',
    'revenue_improvement_guide': 'Revenue improvement guide',
    
    // Enhanced Calendar System
    'team_calendar_overview': 'Team Calendar Overview',
    'consolidated_view_all_team_events': 'Consolidated view of all team events',
    'manual_appointment': 'Manual Appointment',
    'blocked_time': 'Blocked Time',
    'day_off': 'Day Off',
    'total_appointments': 'Total appointments',
    'team_consolidated_view': 'Team consolidated view',
    'unknown_collaborator': 'Unknown collaborator',
    'unknown': 'Unknown',
    'add_collaborator': 'Add Collaborator',
  },
  pt: {
    // Navigation
    'welcome': 'Bem-vindo',
    'search': 'Buscar',
    'services': 'Serviços',
    'profile': 'Perfil',
    'chat': 'Chat',
    'home': 'Início',
    'calendar': 'Calendário',
    'analytics': 'Analytics',
    'notifications': 'Notificações',
    
    // Common
    'loading': 'Carregando...',
    'error': 'Erro',
    'success': 'Sucesso',
    'cancel': 'Cancelar',
    'confirm': 'Confirmar',
    'save': 'Salvar',
    'edit': 'Editar',
    'delete': 'Excluir',
    'back': 'Voltar',
    'next': 'Próximo',
    'previous': 'Anterior',
    'close': 'Fechar',
    
    // Auth
    'login': 'Entrar',
    'register': 'Registrar',
    'logout': 'Sair',
    'email': 'Email',
    'password': 'Senha',
    'name': 'Nome',
    'phone': 'Telefone',
    'location': 'Localização',
    
    // Kompa2Go specific
    'slogan': 'Seu serviço, a um toque',
    'find_book_enjoy': 'Encontre, reserve, aproveite. É assim fácil.',
    'share_location': 'Compartilhar localização',
    'ask_kompi': 'Pergunte ao Kompi',
    'featured_providers': 'Provedores em Destaque',
    'service_categories': 'Categorias de Serviços',
    'my_wallet': 'Minha Carteira',
    'okoins': 'OKoins',
    'booking_passes': 'Passes de Reserva',
    'loyalty_points': 'Pontos de fidelidade',
    'available_balance': 'Saldo disponível',
    'available_passes': 'Passes disponíveis',
    'buy_pass': 'Comprar Passe',
    'upcoming_appointments': 'Próximos Compromissos',
    'no_appointments': 'Nenhum compromisso agendado',
    'popular_services': 'Serviços Populares',
    'manage_business': 'Gerencie seu negócio',
    'appointments_today': 'Compromissos Hoje',
    'rating': 'Avaliação',
    'view_calendar': 'Ver Calendário',
    'collaborators': 'Colaboradores',
    'admin_panel': 'Painel Admin',
    'system_overview': 'Visão geral do sistema',
    'users': 'Usuários',
    'providers': 'Provedores',
    'bookings_today': 'Reservas Hoje',
    'revenue': 'Receita',
    'quick_actions': 'Ações Rápidas',
    'manage_users': 'Gerenciar Usuários',
    'approve_providers': 'Aprovar Provedores',
    'view_transactions': 'Ver Transações',
    'test_users': 'Usuários de Teste',
    'switch_to_client_provider': 'Mudar para Cliente/Provedor',
    'switch_role': 'Mudar Papel',
    'select_role': 'Selecionar Papel',
    'client_mikompa': 'Mi-Kompa (Cliente)',
    'provider_2kompa': '2-Kompa (Provedor)',
    'enter_credentials': 'Digite as credenciais',
    'switching': 'Mudando...',
    'change_role': 'Mudar Papel',
    'language': 'Idioma',
    'spanish': 'Espanhol',
    'english': 'Inglês',
    'portuguese': 'Português',
    
    // Home screen
    'hello': 'Olá',
    'what_service_today': 'Que serviço você precisa hoje?',
    'wallet_balance': 'Saldo disponível',
    'buy_pass_price': 'Comprar Passe (₡500)',
    'search_services': 'Buscar Serviços',
    'switch_to_test_user': 'Mudar para Usuário de Teste',
    'enter_test_credentials': 'Digite as credenciais do usuário de teste:',
    
    // Search screen
    'search_services_title': 'Buscar Serviços',
    'what_service_need': 'Que serviço você precisa?',
    'categories': 'Categorias',
    'providers_count': 'provedores',
    'ask_kompi_what_need': 'Pergunte ao Kompi o que você precisa',
    
    // Profile screen
    'sign_out': 'Sair',
    'sign_out_confirm': 'Tem certeza de que deseja sair?',
    'edit_profile': 'Editar Perfil',
    'update_personal_info': 'Atualize suas informações pessoais',
    'manage_credits_payments': 'Gerencie seus créditos e pagamentos',
    'history': 'Histórico',
    'view_previous_bookings': 'Ver suas reservas anteriores',
    'configuration': 'Configuração',
    'app_preferences': 'Preferências do aplicativo',
    'my_calendar': 'Meu Calendário',
    'manage_availability': 'Gerencie sua disponibilidade',
    'manage_team': 'Gerencie sua equipe',
    'manage_platform': 'Gerenciar a plataforma',
    'user': 'Usuário',
    'administrator': 'Administrador',
    'client': 'Cliente',
    'provider': 'Provedor',
    'available_credits': 'Créditos disponíveis',
    'add_credits': 'Adicionar Créditos',
    'statistics': 'Estatísticas',
    'income': 'Renda',
    
    // Calendar screen
    'month': 'Mês',
    'day': 'Dia',
    'back_to_month': 'Voltar ao Mês',
    'day_agenda': 'Agenda do Dia',
    'available': 'Disponível',
    'add_manual_appointment': 'Adicionar Compromisso Manual',
    'block_time': 'Bloquear Tempo',
    'function_providers_only': 'Esta função é apenas para provedores',
    'client_required': 'Cliente *',
    'service_required': 'Serviço *',
    'time_required': 'Hora *',
    'collaborator_optional': 'Colaborador',
    'client_name': 'Nome do cliente',
    'service_type': 'Tipo de serviço',
    'time_format': 'HH:MM (ex: 14:30)',
    'assign_collaborator': 'Atribuir ao colaborador (opcional)',
    'full_name_required': 'Nome Completo *',
    'alias_required': 'Apelido *',
    'collaborator_name': 'Nome do colaborador',
    'short_name': 'Nome curto ou apelido',
    'avatar': 'Avatar',
    'cancel_kompa2go_booking': 'Cancelar Reserva Kompa2Go',
    'cancel_penalty_warning': 'Cancelar esta reserva resultará em uma penalidade de 4 horas sem aparecer nas buscas. Continuar?',
    'delete_entry': 'Excluir',
    'delete_entry_confirm': 'Tem certeza de que deseja excluir esta entrada?',
    'appointment_added': 'Compromisso adicionado com sucesso',
    'collaborator_added': 'Colaborador adicionado com sucesso',
    'complete_required_fields': 'Por favor, complete todos os campos obrigatórios',
    'complete_name_alias': 'Por favor, complete o nome e apelido',
    'appointments_for': 'Compromissos para',
    'date_required': 'Data *',
    'is_today': 'É hoje',
    'select_date': 'Selecionar data',
    'select_time': 'Selecionar hora',
    'no_collaborator': 'Sem colaborador',
    'assigned_to': 'Atribuído a',
    'scheduling_conflict': 'Conflito de horário',
    'conflict_error_message': 'Conflito de horário. Este horário já está ocupado por outro compromisso ou está bloqueado. Por favor, escolha um horário diferente ou modifique o bloqueio em seu calendário principal.',
    'ok': 'OK',
    'error_adding_appointment': 'Erro ao adicionar compromisso',
    
    // Provider Dashboard
    'programs': 'Programas',
    'sakura_contigo': 'Sakura Contigo',
    'kompa2door': 'Kompa2Door',
    'kraffles': 'Kraffles',
    'program_locked': 'Programa bloqueado',
    'unlock_requirements': 'Requisitos para desbloquear',
    'achievements_required': 'Conquistas necessárias',
    'cost': 'Custo',
    'collaborators_management': 'Gestão de Colaboradores',
    'edit_collaborator': 'Editar Colaborador',
    'block_collaborator': 'Bloquear Colaborador',
    'delete_collaborator': 'Excluir Colaborador',
    'create_credentials': 'Criar Credenciais',
    'username': 'Usuário',
    'assign_services': 'Atribuir Serviços',
    'historical': 'Histórico',
    'completed_services': 'Serviços Concluídos',
    'complaint_filed': 'Reclamação apresentada',
    'complaint_details': 'Detalhes da reclamação',
    'anonymous_complaint': 'Reclamação anônima',
    'improvement_plan': 'Plano de melhoria',
    'configurations': 'Configurações',
    'service_management': 'Gestão de Serviços',
    'add_service': 'Adicionar Serviço',
    'modify_service_restriction': 'Você só pode modificar serviços após 3 meses de atividade',
    'profile_management': 'Gestão de Perfil',
    'business_name': 'Nome do Negócio',
    'work_gallery': 'Galeria de Trabalhos',
    'brand_logo': 'Logo da Marca',
    'promotions': 'Promoções',
    'promotions_locked': 'Promoções bloqueadas até desbloquear conquistas',
    'rating_summary': 'Resumo de Avaliações',
    'total_rated_services': 'Total de serviços avaliados',
    'rating_tips': 'Dicas para manter alta avaliação',
    'services_analytics': 'Análise de Serviços',
    'most_popular_services': 'Serviços mais populares',
    'revenue_breakdown': 'Detalhamento de Receita',
    'filter_by_day': 'Filtrar por dia',
    'filter_by_week': 'Filtrar por semana',
    'filter_by_month': 'Filtrar por mês',
    'yearly_comparison': 'Comparação anual',
    'revenue_improvement_guide': 'Guia de melhoria de receita',
    
    // Enhanced Calendar System
    'team_calendar_overview': 'Visão Geral do Calendário da Equipe',
    'consolidated_view_all_team_events': 'Vista consolidada de todos os eventos da equipe',
    'manual_appointment': 'Compromisso Manual',
    'blocked_time': 'Tempo Bloqueado',
    'day_off': 'Dia de Folga',
    'total_appointments': 'Total de compromissos',
    'team_consolidated_view': 'Vista consolidada da equipe',
    'unknown_collaborator': 'Colaborador desconhecido',
    'unknown': 'Desconhecido',
    'add_collaborator': 'Adicionar Colaborador',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es'); // Spanish as default

  const t = useCallback((key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  }, [language]);

  const changeLanguage = useCallback((newLanguage: Language) => {
    setLanguage(newLanguage);
    console.log(`Language changed to: ${newLanguage}`);
  }, []);

  const value = useMemo(() => ({
    language,
    setLanguage: changeLanguage,
    t
  }), [language, changeLanguage, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}